// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sadzxidzeegbhfabtmvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZHp4aWR6ZWVnYmhmYWJ0bXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTYzMTUsImV4cCI6MjA1OTc5MjMxNX0.iksPhQTlmF9WDX9TCxCFKhDVBIvYhwtgBXPdPgLRhCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);